# This file was generated by GoReleaser. DO NOT EDIT.
cask "orla" do
  name "orla"
  desc "A dead-simple unix tool for lightweight agents"
  homepage "https://github.com/dorcha-inc/orla"
  version "1.2.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "orla"

  on_macos do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-amd64.tar.gz"
      sha256 "6e0154781bd445b0a3ee947094757c0c2640b437b008c77b9b0d536003e6e463"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-darwin-arm64.tar.gz"
      sha256 "23026df2a24dc331afaabe15f2026b377e13189ffd390435b9865406c1edab80"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-amd64.tar.gz"
      sha256 "073d74f8610020205ccf18885d2498b4e4ee0b8a65283f8ceeeef2c01988a287"
    end
    on_arm do
      url "https://github.com/dorcha-inc/orla/releases/download/v#{version}/orla-linux-arm64.tar.gz"
      sha256 "aadc661d97b3cf3f603e87cd129a31f1f1b2d8ae72cadbbfc7f1cbbc9144cb88"
    end
  end

  postflight do
    skip_ollama = ENV["HOMEBREW_ORLA_SKIP_OLLAMA"] == "1"
    if skip_ollama
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew --skip-ollama"
    else
      system "/bin/sh", "-c", "export PATH=\"/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH\" && curl -fsSL https://raw.githubusercontent.com/dorcha-inc/orla/main/scripts/install.sh | sh -s -- --homebrew"
    end
  end

  # No zap stanza required
end
